/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        absolutewhite: "var(--absolutewhite)",
        "color-primitives-alice-blue": "var(--color-primitives-alice-blue)",
        "color-primitives-celestial-blue": "var(--color-primitives-celestial-blue)",
        "color-primitives-columbia-blue": "var(--color-primitives-columbia-blue)",
        "color-primitives-darmonth-green-darmounth-green-500":
          "var(--color-primitives-darmonth-green-darmounth-green-500)",
        "color-primitives-dim-grey": "var(--color-primitives-dim-grey)",
        "color-primitives-gunmental": "var(--color-primitives-gunmental)",
        "color-primitives-indigo-dye": "var(--color-primitives-indigo-dye)",
        "color-primitives-light-gray": "var(--color-primitives-light-gray)",
        "color-primitives-rose-rose-red-150": "var(--color-primitives-rose-rose-red-150)",
        "color-primitives-rose-rose-red-500": "var(--color-primitives-rose-rose-red-500)",
        "color-primitives-tomoatoe-tomatoe-500": "var(--color-primitives-tomoatoe-tomatoe-500)",
        "color-primitives-white": "var(--color-primitives-white)",
        "green-70": "var(--green-70)",
        "green-90": "var(--green-90)",
        "grey-10": "var(--grey-10)",
        "grey-15": "var(--grey-15)",
        "grey-20": "var(--grey-20)",
        "grey-30": "var(--grey-30)",
        "primitives-color": "var(--primitives-color)",
        "primitives-colors-rich-black-200": "var(--primitives-colors-rich-black-200)",
        "token-bg-green": "var(--token-bg-green)",
        "token-border-color": "var(--token-border-color)",
        "token-category-a-marker": "var(--token-category-a-marker)",
        "token-category-b-marker": "var(--token-category-b-marker)",
        "token-category-c-marker": "var(--token-category-c-marker)",
        "token-colors-btn-colors": "var(--token-colors-btn-colors)",
        "token-colors-btn-hover": "var(--token-colors-btn-hover)",
        "token-colors-btn-label": "var(--token-colors-btn-label)",
        "token-colors-btn-light": "var(--token-colors-btn-light)",
        "token-colors-secondary-surface": "var(--token-colors-secondary-surface)",
        "token-colors-subtitle-text": "var(--token-colors-subtitle-text)",
        "token-colors-text-color": "var(--token-colors-text-color)",
        "token-icon-icon-surface-primary": "var(--token-icon-icon-surface-primary)",
        "token-shade-background": "var(--token-shade-background)",
        "token-text-text-surface-btn": "var(--token-text-text-surface-btn)",
        "white-95": "var(--white-95)",
        "white-97": "var(--white-97)",
        "white-99": "var(--white-99)",
      },
      fontFamily: {
        "desktop-button": "var(--desktop-button-font-family)",
        "link-link-regular": "var(--link-link-regular-font-family)",
        "SWIVY-desktop-button": "var(--SWIVY-desktop-button-font-family)",
        "SWIVY-desktop-subtitle": "var(--SWIVY-desktop-subtitle-font-family)",
        "SWIVY-desktop-title": "var(--SWIVY-desktop-title-font-family)",
        "SWIVY-mobile-button": "var(--SWIVY-mobile-button-font-family)",
        "SWIVY-mobile-subtitle": "var(--SWIVY-mobile-subtitle-font-family)",
        "SWIVY-mobile-title": "var(--SWIVY-mobile-title-font-family)",
      },
    },
  },
  plugins: [],
};
